apiVersion: apps/v1
kind: Deployment
metadata:
  name: slsa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slsa-demo
  template:
    metadata:
      labels:
        app: slsa-demo
    spec:
      imagePullSecrets:
        - name: ghcrsecret
      containers:
        - name: app
          image: ghcr.io/ori5r2/slsa:sha-d39f42a45944cc7c64c06e312ca46e82f97d4a7b
          ports:
            - containerPort: 8080
