apiVersion: apps/v1
kind: Deployment
metadata:
  name: slsa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slsa-demo
  template:
    metadata:
      labels:
        app: slsa-demo
    spec:
      imagePullSecrets:
        - name: ghcrsecret
      containers:
        - name: app
          image: ghcr.io/ori5r2/slsa:sha-46e0afe65c497b43d461b4c0e79f0987bccdba23
          ports:
            - containerPort: 8080
